### ISSUE TITLE
在componentWillReceiveProps（props）处理多个返回结果

### ISSUE THREAD

**Issue by sirhu11** [sujianqingfeng/rn-wanandroid#1]
假如登陆前先获取验证码，获取验证码的返回结果在componentWillReceiveProps（props）方法里面处理，在执行登陆，登陆的返回结果也在componentWillReceiveProps（props）方法里面处理，这样怎么区分这两个返回结果。
componentWillReceiveProps(props) {
        console.log('loginPage componentWillReceiveProps doLogin',
            props.isLogin, props.loginComplete, props.loginSuccess, props.loginData);
        if (props.isLogin) {
            this.refs.toast.show('正在登录', DURATION.LENGTH_SHORT);
        } else if (props.loginSuccess) {
            this.refs.toast.show('登录成功', DURATION.LENGTH_SHORT);
        } else if (props.loginComplete) {
            this.refs.toast.show('登录失败', DURATION.LENGTH_SHORT);
        }

        console.log('loginPage componentWillReceiveProps doGetVcode',
            props.isGetVcode, props.getVcodeComplete, props.getVcodeSuccess, props.getVcodeData);
        if (props.isGetVcode) {
            this.refs.toast.show('正在获取', DURATION.LENGTH_SHORT);
        } else if (props.getVcodeSuccess) {
            this.refs.toast.show('获取成功', DURATION.LENGTH_SHORT);
        } else if (props.getVcodeComplete) {
            this.refs.toast.show('获取失败', DURATION.LENGTH_SHORT);
        }
    }

**Comment by sujianqingfeng** [comment]
可以一个标识 在state中，比如action， action为0的时候 得到验证码  1的时候为登录 等等 在不同的操作的时候，赋予action不同的值

**Comment by sirhu11** [comment]
获取验证码 和 登陆，这两个操作我是用了两个不同的reducer【loginReducer，getVcodeReducer】，这两个操作要怎么共用State中的一个标识呢？
loginReducer：【
const defaultState = {
    isLogin: false,//是否正在登陆
    loginComplete: false,//是否登陆完成，成功或失败
    loginSuccess: false,//是否登陆成功
    loginData: '',//返回数据
};

export default function reduceLogin(state = defaultState, action) {
    switch (action.type) {
        case loginTypes.LOGIN_DOING:
            return {
                ...state,
                isLogin: true,
                loginComplete: false,
                loginSuccess: false,
                loginData: '',
            };
        case loginTypes.LOGIN_DONE:
            return {
                ...state,
                isLogin: false,
                loginComplete: true,
                loginSuccess: true,
                loginData: action.loginData,
            };
        case loginTypes.LOGIN_ERROR:
            return {
                ...state,
                isLogin: false,
                loginComplete: true,
                loginSuccess: false,
                loginData: action.loginData,
            };
        default:
            return state;
    }
};
】
getVcodeReducer：【
const defaultState = {
    isGetVcode: false,
    getVcodeComplete: false,
    getVcodeSuccess: false,
    getVcodeData: '',
};

export default function reduceGetVcode(state = defaultState, action) {
    switch (action.type) {
        case getVcodeTypes.GET_VCODE_DOING:
            return {
                ...state,
                isGetVcode: true,
                getVcodeComplete: false,
                getVcodeSuccess: false,
                getVcodeData: '',
            };
        case getVcodeTypes.GET_VCODE_DONE:
            return {
                ...state,
                isGetVcode: false,
                getVcodeComplete: true,
                getVcodeSuccess: true,
                getVcodeData: action.getVcodeData,
            };
        case getVcodeTypes.GET_VCODE_ERROR:
            return {
                ...state,
                isGetVcode: false,
                getVcodeComplete: true,
                getVcodeSuccess: false,
                getVcodeData: action.getVcodeData,
            };
        default:
            return state;
    }
};
】

**Comment by sujianqingfeng** [comment]
可以用移到一个reduce  或者通过dispatch修改其他reduce里面的state值

**Comment by sirhu11** [comment]
好的，谢谢，明白你的意思了。
