### ISSUE TITLE
cookie数据获取

### ISSUE THREAD

**Issue by mirse** [sujianqingfeng/rn-wanandroid#5]
想请教下如何获取登录返回的cookie信息呢？

**Comment by sujianqingfeng** [comment]
不好意思，刚才看到这个issue。这个项目很久都没有更新过了，最近都折腾flutter去了。
wanandroid的user/login接口，登陆成功后，response的头部里面，有一个set-cookie的属性，你把值保存下来，然后需要鉴权的接口你带上这个cookie就可以了，我这个项目我刚看了下，在HttpUtil.js里面，可以看看。

**Comment by mirse** [comment]
那个我看了set-cookie属性里携带的数据并没有用户名或密码之类的数据，我收藏时带上这个cookie还是一直显示未登录，是接口数据有变化了吗？谢谢了

**Comment by sujianqingfeng** [comment]
![image](https://user-images.githubusercontent.com/16167459/55633293-9da24080-57ee-11e9-9814-db13fc116bce.png)
把这些cookie全部保存下来，后面的请求带上这些cookie，wanAndroid有接口文档的。

**Comment by mirse** [comment]
![image](https://user-images.githubusercontent.com/5188922/55663028-45019080-584c-11e9-89db-d7e366fe06a3.png)
我用这个拿到的cookie数据

![image](https://user-images.githubusercontent.com/5188922/55663059-7da16a00-584c-11e9-9577-a245e04196a6.png)

明显跟postman看到的不一样，是我有方法用错了吗?

**Comment by sujianqingfeng** [comment]
![image](https://user-images.githubusercontent.com/16167459/55666305-937c5280-587f-11e9-8a62-d1d8791150a0.png)
![image](https://user-images.githubusercontent.com/16167459/55666314-b149b780-587f-11e9-8d88-129f59c8985a.png)
实际只要这个JSESSIONID这个就可以了，你把你所有的response中的cookie打印出来嘛

**Comment by mirse** [comment]
我就拿到了response的头部里的set-cookie的数据，其余的该怎么拿呢

**Comment by sujianqingfeng** [comment]
![image](https://user-images.githubusercontent.com/16167459/55667103-af392600-588a-11e9-9362-f185c5c55323.png)
这个数据就是在set-cookie里面呀，你确定你打印完毕没有，可以debug调试一下这里的返回头信息。

**Comment by mirse** [comment]
![image](https://user-images.githubusercontent.com/5188922/55669809-6bf0ae80-58ae-11e9-8368-7920979a8160.png)

以上是我拿到的response信息。。。，很奇怪拿不到跟你一样的
![image](https://user-images.githubusercontent.com/5188922/55669821-9d697a00-58ae-11e9-94a6-c92da38b9ddc.png)

**Comment by sujianqingfeng** [comment]
![image](https://user-images.githubusercontent.com/16167459/55669997-ffc37a00-58b0-11e9-928a-fc10ef3f4e53.png)
我用node试了下，是有的呀。

**Comment by mirse** [comment]
方便帮我看下代码吗，我现在卡这里=-=，没招了，可以的话留个邮箱，谢谢了

**Comment by mirse** [comment]
`  _loginUa(ua,ps){

        let formData = new FormData()
        formData.append('username',ua)
        formData.append('password',ps)

        let LOGIN_URL = 'https://www.wanandroid.com/user/login';
        fetch(LOGIN_URL,{
            method:'POST',
            body:
            formData
            ,
        })
            .then((response)=> {
                console.warn(response.headers.raw)
                if (response.headers.map.hasOwnProperty('set-cookie')){
                    //console.warn(response.headers.map['set-cookie'])
                   // AsyncStorageUtils.save('cookie',response.headers.map['set-cookie'])
                }
                   return  response.json()
                }
                )
            .then((responseData)=>{

                //注册成功返回的数据： responseData:{"data":{"chapterTops":[],"collectIds":[],"email":"","icon":"","id":21197,
                // "password":"","token":"","type":0,"username":"menghuanqv1"},"errorCode":0,"errorMsg":""
                // }}

                //注册失败返回数据：responseData:{"data":null,"errorCode":-1,"errorMsg":"用户名已经被注册"}
                if (responseData.errorCode === 0){
                    AsyncStorageUtils.save("ua",ua)
                    AsyncStorageUtils.save("ps",ps)
                    this.props.navigation.state.params.callback(responseData.data.username);
                    this.props.navigation.goBack();
                    Toast.show("登录成功!")
                }
                this.setState({
                    msg:responseData
                })
              //  console.warn("responseData:"+JSON.stringify(responseData));
            })
            .catch((error) => {
                // alert(error)
                callback(error);
            });
    }`

这块是我登陆模块的代码=-=

**Comment by sujianqingfeng** [comment]
我QQ 121116111
我好久都没有写过RN了，我等会写一个Demo看看。我现在在外面。
