### ISSUE TITLE
关于RN

### ISSUE THREAD

**Issue by startfromandroid** [sujianqingfeng/rn-wanandroid#6]
楼主感觉最近RN怎样啊，打算入坑

**Comment by sujianqingfeng** [comment]
你好，我说说的感觉。
现在原生还是主流，然后混入RN Flutter这类的。先把自己原生这一块给弄的扎扎实实的，不要像我这个半罐水。然后才学习这些作为扩充，最为一个加分技能，之前打算用RN替换公司的原生，发现不大可能。
RN很久没怎么关注了，因为去关注Flutter，如果让我从里面选择一个，我选择Flutter。
RN学习肯定是可以的，不知道新版本怎么样了😀
